// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHvXKjSNNcCcxlLmkmjUcATV-AZObk3Os',
    appId: '1:412638323904:web:4c14ae6b388fd565f37925',
    messagingSenderId: '412638323904',
    projectId: 'productoraempacadora',
    authDomain: 'productoraempacadora.firebaseapp.com',
    storageBucket: 'productoraempacadora.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdl1fS-r_Tbxb-XObLHPA-Qmx5ZFddZTs',
    appId: '1:412638323904:android:1ec181cee7274352f37925',
    messagingSenderId: '412638323904',
    projectId: 'productoraempacadora',
    storageBucket: 'productoraempacadora.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHvXKjSNNcCcxlLmkmjUcATV-AZObk3Os',
    appId: '1:412638323904:web:e31f7fd4a7ec409df37925',
    messagingSenderId: '412638323904',
    projectId: 'productoraempacadora',
    authDomain: 'productoraempacadora.firebaseapp.com',
    storageBucket: 'productoraempacadora.firebasestorage.app',
  );
}
